### ISSUE TITLE
Tests/run.sh failed

### ISSUE THREAD

**Issue by junchenfeng** [17zuoye/luiti#1]
[test] test_main.py
[reset date by week] from 2015-02-17T10:57:58.328021+08:00 to 2015-02-16T00:00:00+08:00
[reset date by week] from 2015-02-10T10:57:58.329288+08:00 to 2015-02-09T00:00:00+08:00
.[reset date by week] from 2014-09-01T09:00:00+08:00 to 2014-09-01T00:00:00+08:00
[info] 2014-09-01T09:00:00+08:00  is not in  {'weekday_num': [1], 'hour_num': [5, 6, 7, 8]} , so the task exited.
[reset date by week] from 2014-09-02T06:28:00+08:00 to 2014-09-01T00:00:00+08:00
[info] 2014-09-02T06:28:00+08:00  is not in  {'weekday_num': [1], 'hour_num': [5, 6, 7, 8]} , so the task exited.
[reset date by week] from 2014-09-01T04:28:00+08:00 to 2014-09-01T00:00:00+08:00
[info] 2014-09-01T04:28:00+08:00  is not in  {'weekday_num': [1], 'hour_num': [5, 6, 7, 8]} , so the task exited.
[reset date by week] from 2014-09-01T05:00:00+08:00 to 2014-09-01T00:00:00+08:00
[reset date by week] from 2014-09-01T06:28:00+08:00 to 2014-09-01T00:00:00+08:00
[reset date by week] from 2014-09-01T08:59:00+08:00 to 2014-09-01T00:00:00+08:00
## .

Ran 2 tests in 0.575s

OK
[test] test_utils.py
## ....

Ran 4 tests in 0.174s

OK
[test] test_task.py
[reset date by week] from 2014-09-02T00:00:00+08:00 to 2014-09-01T00:00:00+08:00
## .

Ran 1 test in 0.163s

OK
[test] test_luiti_ext.py
# E.EEE
## ERROR: test_multiple_luiti_tasks (**main**.TestLuiti)

Traceback (most recent call last):
  File "tests/test_luiti_ext.py", line 40, in test_multiple_luiti_tasks
    DDay = manager.load_a_task_by_name("DDay")
  File "/home/junchen/git/luiti/luiti/manager/setup_packages.py", line 51, in new_func
    return orig_func(_args, *_kwargs) # call it at last.
  File "/home/junchen/git/luiti/luiti/manager/loader.py", line 52, in load_a_task_by_name
    task_lib     = lc.import2(package_path)
  File "/home/junchen/git/luiti/luiti/manager/config.py", line 21, in import2
    return **import**(a_package, None, None, 'non_empty')
  File "/home/junchen/git/luiti/tests/project_A/luiti_tasks/d_day.py", line 3, in <module>
    from .__setup import *
ImportError: No module named __setup
# 
## ERROR: test_ref_tasks (**main**.TestLuiti)

Traceback (most recent call last):
  File "tests/test_luiti_ext.py", line 22, in test_ref_tasks
    ADay = manager.load_a_task_by_name("ADay")
  File "/home/junchen/git/luiti/luiti/manager/setup_packages.py", line 51, in new_func
    return orig_func(_args, *_kwargs) # call it at last.
  File "/home/junchen/git/luiti/luiti/manager/loader.py", line 52, in load_a_task_by_name
    task_lib     = lc.import2(package_path)
  File "/home/junchen/git/luiti/luiti/manager/config.py", line 21, in import2
    return **import**(a_package, None, None, 'non_empty')
  File "/home/junchen/git/luiti/tests/project_A/luiti_tasks/a_day.py", line 3, in <module>
    from .__setup import *
ImportError: No module named __setup
# 
## ERROR: test_run_python_on_distributed_system (**main**.TestLuiti)

Traceback (most recent call last):
  File "tests/test_luiti_ext.py", line 96, in test_run_python_on_distributed_system
    DDay      = manager.load_a_task_by_name("DDay")
  File "/home/junchen/git/luiti/luiti/manager/setup_packages.py", line 51, in new_func
    return orig_func(_args, *_kwargs) # call it at last.
  File "/home/junchen/git/luiti/luiti/manager/loader.py", line 52, in load_a_task_by_name
    task_lib     = lc.import2(package_path)
  File "/home/junchen/git/luiti/luiti/manager/config.py", line 21, in import2
    return **import**(a_package, None, None, 'non_empty')
  File "/home/junchen/git/luiti/tests/project_A/luiti_tasks/d_day.py", line 3, in <module>
    from .__setup import *
ImportError: No module named __setup
# 
## ERROR: test_serialize_and_unserialize (**main**.TestLuiti)

Traceback (most recent call last):
  File "tests/test_luiti_ext.py", line 72, in test_serialize_and_unserialize
    serialize_and_unserialize_a_task_instance('ADay', pickle)
  File "tests/test_luiti_ext.py", line 60, in serialize_and_unserialize_a_task_instance
    task_cls               = manager.load_a_task_by_name(cls_name)
  File "/home/junchen/git/luiti/luiti/manager/setup_packages.py", line 51, in new_func
    return orig_func(_args, *_kwargs) # call it at last.
  File "/home/junchen/git/luiti/luiti/manager/loader.py", line 52, in load_a_task_by_name
    task_lib     = lc.import2(package_path)
  File "/home/junchen/git/luiti/luiti/manager/config.py", line 21, in import2
    return **import**(a_package, None, None, 'non_empty')
  File "/home/junchen/git/luiti/tests/project_A/luiti_tasks/a_day.py", line 3, in <module>
    from .__setup import *
ImportError: No module named __setup

---

Ran 5 tests in 0.009s

FAILED (errors=4)
[test] test_mr_test_case.py
Traceback (most recent call last):
  File "tests/test_mr_test_case.py", line 17, in <module>
    class TestMrTestCase(unittest.TestCase):
  File "/home/junchen/git/luiti/luiti/mr_test_case.py", line 50, in MrTestCase
    setattr(cls, test_method_name, generate_closure_function(mr_task_name1))
  File "/home/junchen/git/luiti/luiti/mr_test_case.py", line 32, in generate_closure_function
    task_cls      = Loader.load_a_task_by_name(mr_task_name1) # keep it!
  File "/home/junchen/git/luiti/luiti/manager/setup_packages.py", line 51, in new_func
    return orig_func(_args, *_kwargs) # call it at last.
  File "/home/junchen/git/luiti/luiti/manager/loader.py", line 52, in load_a_task_by_name
    task_lib     = lc.import2(package_path)
  File "/home/junchen/git/luiti/luiti/manager/config.py", line 21, in import2
    return **import**(a_package, None, None, 'non_empty')
  File "/home/junchen/git/luiti/tests/project_A/luiti_tasks/foobar_day.py", line 3, in <module>
    from .__setup import *
ImportError: No module named __setup

**Comment by dchentech** [comment]
Thanks for the first report issue , here's the commit which fixed it. https://github.com/17zuoye/luiti/commit/e0ac0333ae8db9ae7a8f092a0f82ba5ac204c4d1 .  I forgot to clean .pyc cache.

**Comment by junchenfeng** [comment]
It works
